import React from "react";
import Head from "next/head";
import TopBar from "../../components/topbar";
import SortTable from "../../components/table/sort-table";
import { shedHeadings } from "../../constants/tableHeadings";
import { shedBody } from "../../constants/tableBody";
import { tableHeadings } from "./../../constants/tableHeadings";

function Sheds() {
  const information = [
    {
      farmerId: "#2333",
      numberOfBirds: 500,
      dailyFeedQuantity: 300,
    },
    {
      farmerId: "#2333",
      numberOfBirds: 500,
      dailyFeedQuantity: 300,
    },
  ];
  return (
    <>
      <Head>
        <title>Sheds</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full h-screen">
        <div className="w-full h-full ">
          <div className="w-full h-[10%] border-4 border-black">
            <TopBar />
          </div>
          <div className="w-full h-[87%] overflow-y-scroll mt-[1.5%] border-4 border-black">
            <div className="  h-full ">
              <SortTable
                headings={tableHeadings.shedHeadings}
                // body={shedBody.request}
                data={information}
                type={"shedBody"}
              />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export default Sheds;
