import Image from "next/image";
import Head from "next/head";
import TopBar from "../components/topbar";
import StatsContainer from "../components/statsContainer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full h-screen">
        <div className="w-full h-full bg-b ">
          <div className="w-full h-[10%] border-4 border-black">
            <TopBar />
          </div>

          {/* 1st row */}
          <div className="w-full flex flex-row border border-red-500 py-5 px-5 gap-5">
            {/* statsContainer */}
            <div className="w-[75%] border border-green-600 py-5 flex justify-center">
              <StatsContainer />
            </div>
            {/* Top Employee */}
            <div className="w-[25%] border border-green-500 flex flex-col gap-5">
              {/* <div className="bg-red-400 py-10 px-5"></div>
              <div className="bg-red-400 py-10 px-5"></div> */}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
