import React from "react";
import Head from "next/head";
import TopBar from "../../components/topbar";
import { useMemo, useEffect, useState } from "react";
import { useSession, signIn } from "next-auth/react";
import { ENDPOINTS } from "../../constants/endpoints";
import { shedRecordAxios } from "../../tools/libraries/axios";

import ShedRecordsModal from "../../components/shedRecordsModal";

const Records = () => {
  const [showModal, setShowModal] = useState(false);

  const [shedRecords, setShedRecords] = useState([]);
  // const [shed2Records, setShed2Records] = useState([]);
  // const [shed3Records, setShed3Records] = useState([]);
  // const [shed4Records, setShed4Records] = useState([]);
  // const [shed5Records, setShed5Records] = useState([]);
  // const [shed6Records, setShed6Records] = useState([]);

  const { data: session } = useSession();

  const token = session?.user?.accessToken;

  useEffect(() => {
    // if (!session) {
    //   signIn();
    // }
  }, [session]);

  const information = [
    {
      shedID: 1,
      farmerID: 123,
      collectionPeriod: 10,
      feedQuantity: 100,
      numberOfCrates: 100,
      numberOfEggPieces: 3000,
      numberOfBrokenEggs: 0,
      deadBirds: 5,
    },
  ];

  const getShedRecords = (shedId) => {
    shedRecordAxios
      .get(`${ENDPOINTS.GET_RECORDS_BY_SHED_ID}/${shedId}`, {
        headers: { Authorization: `Bearer ${token}` },
      })
      .then((result) => {
        console.log(result.data);
        setShedRecords(result.data);
      })
      .catch((err) => console.log(err));
  };

  return (
    <>
      <Head>
        <title>Orders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-full">
        <div className="w-full h-full">
          <div className="w-full h-[10%]">
            <TopBar />
          </div>
          <div className="w-full h-[87%] overflow-y-scroll mt-[1.5%]">
            {showModal && (
              <ShedRecordsModal
                setShowModal={setShowModal}
                data={shedRecords}
              />
            )}
            <div className="flex flex-row items-center justify-between h-full">
              <div className="w-[50%] h-[100%] flex flex-col items-center justify-between">
                <div
                  onClick={() => {
                    setShowModal(true);
                    getShedRecords(1);
                  }}
                  className="h-[40%] bg-white w-[70%] m-10 flex items-center justify-center rounded-2xl"
                >
                  Shed One
                </div>
                <div
                  onClick={() => {
                    setShowModal(true);
                    getShedRecords(2);
                  }}
                  className="h-[40%] bg-white w-[70%] m-10 flex items-center justify-center rounded-2xl"
                >
                  Shed Three
                </div>
                <div
                  onClick={() => {
                    setShowModal(true);
                    getShedRecords(5);
                  }}
                  className="h-[40%] bg-white w-[70%] m-10 flex items-center justify-center rounded-2xl"
                >
                  Shed Five
                </div>
              </div>
              <div className="w-[50%] h-[100%] flex flex-col items-center justify-between">
                <div
                  onClick={() => {
                    setShowModal(true);
                    getShedRecords(2);
                  }}
                  className="h-[40%] bg-white w-[70%] m-10 flex items-center justify-center rounded-2xl"
                >
                  Shed Two
                </div>
                <div
                  onClick={() => {
                    setShowModal(true);
                    getShedRecords(4);
                  }}
                  className="h-[40%] bg-white w-[70%] m-10 flex items-center justify-center rounded-2xl"
                >
                  Shed Four
                </div>
                <div
                  onClick={() => {
                    setShowModal(true);
                    getShedRecords(6);
                  }}
                  className="h-[40%] bg-white w-[70%] m-10 flex items-center justify-center rounded-2xl"
                >
                  Shed Six
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Records;
