import React from "react";
import Head from "next/head";
import TopBar from "../../components/topbar";
import SortTable from './../../components/table/sort-table';
import { tableHeadings } from "../../constants/tableHeadings";

function Orders() {
  const orderInformation =[{
    farmerID:1,
    customerName:"Roxanne Aryee",
    numberOfCrates:200,
    orderDate:"2022-05-01",
    customerPhoneNumber:"+233507111876"
  }]
  return (
    <>
      <Head>
        <title>Orders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full h-screen">
        <div className="w-full h-full ">
          <div className="w-full h-[10%] border-4 border-black">
            <TopBar />
          </div>
          <div className="w-full h-[87%] overflow-y-scroll mt-[1.5%] border-4 border-black">
            <div className="h-full">
              <SortTable
                headings={tableHeadings.orderHeadings}
                // body={orderBody.request}
                data={orderInformation}
                type={"orderBody"}
              />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export default Orders;
